name: Frontend Automating Containerization

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Frontend Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "shahid0404" --password-stdin 
        FRONTEND_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t final-project-frontend ./frontend
        docker tag final-project-frontend shahid0404/final-project-frontend:$FRONTEND_TAG
        docker push shahid0404/final-project-frontend:$FRONTEND_TAG